n = input('Digite algo: ')
print('O tipo primitivo desse valor e {}'.format(type(n)))
print('Só tem espaços? {}'.format(n.isspace()))
print('E um número? {}'.format(n.isnumeric()))
print('E alfabetico? {}'.format(n.isalpha()))
print('E alfanumerico? {}'.format(n.isalnum()))
print('Está em maiusculo? {}'.format(n.isupper()))
print('Está em minusculo? {}'.format(n.islower()))
print('Está capitalizado? {}'.format(n.istitle()))
